services:
  srvrmon:
    build: .
    image: weasts/srvrmon:latest
    container_name: live-server-monitor
    ports:
      - "8501:8501"
    pid: "host"
    privileged: true
    environment:
      - POLLING_INTERVAL_MS=5000
      - STORAGE_PATHS=/host_root
      - LOG_CONFIG=Host Syslog:/host_root/var/log/syslog
    volumes:
      - /:/host_root:ro
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    devices: 
      - /dev/dri:/dev/dri
    deploy: 
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
